name: Generate ARM Template from bicep to deploy with button

on:
  push:
    paths:
      - '**/*.bicep'

jobs:
  bicep-to-arm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate ARM template
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: infra.bicep
        outputFilePath: infra.json

    - name: Commit and push ARM template
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Autogenerate ARM template'
        add_files: 'infra.json'
        push: true

