name: Build zip and set to release

on: 
  push:
    tags:
    - '*'

env:
  AZURE_FUNCTIONAPP_NAME: defender-for-vm-analyzer # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                 # set this to the Python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub action'
      uses: actions/checkout@v2

    - name: 'Run docker oryx build'
      uses: addnab/docker-run-action@v3
      with:
          image: mcr.microsoft.com/oryx/build:latest
          options: -v ${{ github.workspace }}:/repo
          run: oryx build /repo --output /repo

    - name: Zip everything
      run: zip -r release.zip *

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        omitBody: true